# Generated by Django 6.1 on 2026-08-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(help_text='آیدی عددی منحصر به فرد کاربر در تلگرام', unique=True)),
                ('business_connection_id', models.CharField(help_text='شناسه اتصال بیزینس دریافتی از تلگرام', max_length=255, unique=True)),
                ('first_name', models.CharField(blank=True, help_text='نام اول کاربر', max_length=100, null=True)),
                ('username', models.CharField(blank=True, help_text='نام کاربری تلگرام', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن اتصال')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='تاریخ ایجاد رکورد')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='تاریخ آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'اکانت بیزینس',
                'verbose_name_plural': 'اکانت\u200cهای بیزینس',
                'ordering': ['-created_at'],
            },
        ),
    ]
